# Project information
site_name: SSL Wiki
site_url: https://www.ssl-wiki.com/
site_author: SYLG
site_description: Robocup Small Size League 教培系统
docs_dir: build
# Repository
repo_name: SY-LG/SSL-Wiki
repo_url: https://github.com/SY-LG/SSL-Wiki

# Copyright
copyright: Copyright &copy; 2023 SYLG

# Configuration
theme:
  name: material
  custom_dir: build/overrides
  language: zh
  features:
    # - announce.dismiss
    - content.action.edit
    - header.autohide
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    logo: logo
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
    annotation: material/chevron-right-circle
      # note: octicons/tag-16
      # abstract: octicons/checklist-16
      # info: octicons/info-16
      # tip: octicons/squirrel-16
      # success: octicons/check-16
      # question: octicons/question-16
      # warning: octicons/alert-16
      # failure: material/license
      # danger: octicons/zap-16
      # bug: octicons/bug-16
      # example: octicons/beaker-16
      # quote: octicons/quote-16
      # champion: fontawesome/solid/champagne-glasses
    # - toc.integrate
  palette:
    - scheme: default
      primary: custom
      # accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      # accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Noto Sans SC
    code: Fira Code
  favicon: assets/images/favicon.svg
  logo: assets/images/logo.jpg


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SY-LG
  generator: false
  background:
    homepage: 'assets/background-image.jpg'  # 首页背景图片
    not_homepage: 'assets/not-background-image.jpg'  # 非首页背景图片

# Plugins
plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: none
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      auto_caption: false
      caption_position: bottom
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html  
  - pymdownx.critic
  - pymdownx.tilde  
  - pymdownx.caret
  - pymdownx.details

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys  
  - pymdownx.mark
  - pymdownx.smartsymbols  
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true

  # - pymdownx.magiclink:
  #     repo_url_shorthand: true
  #     user: squidfunk
  #     repo: mkdocs-material

  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
# nav:
#   - 第 0 章:SRC整体框架:    
#     - 0.1 SJTU_SRC:
#       - 0.1.1 上海交通大学SRC赛队章程: # 我看原来的wiki做了,但没有放进去
#       - 0.1.2 SRC名人堂: # 放下历代火影,有贡献的人, 或者每年的奖项之类的
#       - 0.1.3 各个组的介绍: # 详细的介绍一下每个组的任务之类的
#     - 0.2 实车调试流程: # 我把原来关于软件之类的全放这里面了
#       - 0.2.1 falcon:
#       - 0.2.2 视觉机:
#       - 0.2.3 Cray:
#       - 0.2.4 发射机:
#       - 0.2.5 车的拨码,开机之类的:
#       - 0.2.6 AutoReferee:
#   - 第 1 章:软件:
#     - 软件开发统一规范: # 我感觉这是新人入住第一课
#       - git 统一开发流程:
#       - 变量命名统一规范:
#       - 状态机写法:
#     - 1.1 软件整体流程: # 这得要靠组长
#     - 1.2 lua: # 可以优先完成这一部分方便校内赛新生
#     - 1.3 C++:
#         - 1.3.1 skill:
#         - 1.3.2 worldmodel: # 这些偏底层的可以稍后完成?(感觉难度也会大一点)
#         - 1.3.3 motioncontrol:
#   - 第 2 章:电控:
#   - 第 3 章:硬件: 
# Page tree
nav:
  - 第 0 章 &nbsp;  SJTU_SRC:
    - chapter_preface/index.md
    - 0.1. &nbsp; 什么是Robocup SSL: chapter_preface/what_is_ssl.md
    - 0.2. &nbsp; SRC赛队章程: chapter_preface/上海交通大学SRC赛队章程.md
    - 0.3. &nbsp; 关于本教培系统: chapter_preface/about_the_book.md

  - 第 1 章 &nbsp; &nbsp; 实车调试流程:
    - chapter_universal_build/index.md
    - 1.1. &nbsp; 环境搭建: chapter_universal_build/SRC 开发环境搭建教程.md
    - 1.2. &nbsp; falcon: chapter_universal_build/falcon.md
    - 1.3. &nbsp; 视觉机: chapter_universal_build/视觉机.md
    - 1.4. &nbsp; 裁判盒: chapter_universal_build/裁判盒.md
    - 1.5. &nbsp; 发射机与机器人: chapter_universal_build/发射机与机器人.md
    - 1.6. &nbsp; 参数标定: chapter_universal_build/参数标定.md 

  - 第 2 章 &nbsp; &nbsp; 软件与算法:
    - chapter_software/index.md
    - 2.1 &nbsp; cpp:
      - 2.1.1 &nbsp; 跑一个程序发生了什么: chapter_software/sub_chapter_cpp/跑一个程序发生了什么.md
      - 2.1.2 &nbsp; 单例与指针: chapter_software/sub_chapter_cpp/单例与指针.md
    - 2.2 &nbsp; lua:
      - chapter_software/sub_chapter_lua/index.md
      - 2.2.1 &nbsp; lua基本语法: chapter_software/sub_chapter_lua/lua基本语法.md
      - 2.2.2 &nbsp; 特殊的lua: chapter_software/sub_chapter_lua/config.md
      - 2.2.3 &nbsp; 脚本选择: chapter_software/sub_chapter_lua/脚本选择.md
      - 2.2.4 &nbsp; SRC中的lua: chapter_software/sub_chapter_lua/lua_in_SRC.md
      - 2.2.5 &nbsp; lua中的skill: chapter_software/sub_chapter_lua/lua中的skill.md
      - 2.2.6 &nbsp; lua中的工具函数: chapter_software/sub_chapter_lua/lua中的工具函数.md
      - 2.2.7 &nbsp; rolematch模块: chapter_software/sub_chapter_lua/Rolematch模块.md
    - 2.3 &nbsp; skill: 
      - chapter_software/sub_chapter_skill/index.md
      - 2.3.1 &nbsp; advance: chapter_software/sub_chapter_skill/advance.md
      - 2.3.2 &nbsp; marking: chapter_software/sub_chapter_skill/MarkingPosV2.md

  - 第 3 章 &nbsp; &nbsp; 电控:
    - chapter_electronics/index.md
    - 3.1 &nbsp; 电机驱动: 
      - chapter_electronics/sub_chapter_motor/index.md
    - 3.2 &nbsp; 电路:
      - chapter_electronics/sub_chapter_circuit/index.md
      - 3.2.1 &nbsp; 功率板: chapter_electronics/sub_chapter_circuit/power_board.md 
    - 3.3 &nbsp; 控制算法:
      - chapter_electronics/sub_chapter_control/index.md
      - 3.3.1 &nbsp; 代码烧写: chapter_electronics/sub_chapter_control/小车代码烧写方法.md
    - 3.4 &nbsp; 通信:
      - chapter_electronics/sub_chapter_communication/index.md

  - 第 4 章 &nbsp; &nbsp; 硬件:
    - chapter_hardware/index.md
    - 4.1 &nbsp; 车身硬件结构: chapter_hardware/body.md
    
